# Generated by Django 4.0.4 on 2022-04-16 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('proprietor', 'first_name', 'last_name', 'phone_number')},
        ),
    ]
