# Generated by Django 4.0.4 on 2022-04-19 21:04

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[main_app.models.greater_than_today]),
        ),
    ]
